# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoProject
  pod ‘GoogleSignIn’

  target 'demoProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoProjectUITests' do
    # Pods for testing
  end

end
